// <auto-generated />
using EBOS.CRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EBOS.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260219170000_RemoveValidationRuleTenantId")]
    partial class RemoveValidationRuleTenantId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
