// <auto-generated />
using System;
using EBOS.CRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBOS.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260201095949_ChangeStructure")]
    partial class ChangeStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.AddressType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowsMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequiresPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("AddressTypes", "EBOS");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("BetweenStreet1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BetweenStreet2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("ExternalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InternalNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Neighbourhood")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("City", "StateOrProvince")
                        .HasDatabaseName("IX_Address_City_State");

                    b.HasIndex("CountryId", "City")
                        .HasDatabaseName("IX_Address_Country_City");

                    b.ToTable("Addresses", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_Address_GoogleMapsUrl_Valid", "[GoogleMapsUrl] IS NULL OR [GoogleMapsUrl] LIKE 'https://maps.%'");

                            t.HasCheckConstraint("CK_Address_Latitude_Range", "[Latitude] IS NULL OR ([Latitude] BETWEEN -90 AND 90)");

                            t.HasCheckConstraint("CK_Address_Longitude_Range", "[Longitude] IS NULL OR ([Longitude] BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_Address_PostalCode_Length", "LEN([PostalCode]) >= 3");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BankInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bic")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("BankInformation", "CRM");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BranchOffice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CorporateCustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CorporateCustomerId")
                        .HasDatabaseName("IX_BranchOffice_CorporateCustomerId");

                    b.ToTable("BranchOffices", "CRM");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BranchOfficeAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchOfficeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BranchOfficeId", "IsCurrent", "IsPrimary")
                        .HasDatabaseName("IX_BranchOfficeAddress_Current_Primary");

                    b.ToTable("BranchOfficeAddresses", "CRM");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CreditAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditAccount_CustomerId");

                    b.ToTable("CreditAccounts", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_CreditAccount_MaxAmount_Positive", "[MaxAmount] > 0");

                            t.HasCheckConstraint("CK_CreditAccount_UsedAmount_NonNegative", "[UsedAmount] >= 0");

                            t.HasCheckConstraint("CK_CreditAccount_UsedAmount_WithinLimit", "[UsedAmount] <= [MaxAmount]");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CreditTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("CreditAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreditAccountId")
                        .HasDatabaseName("IX_CreditTransactions_CreditAccountId");

                    b.HasIndex("CreditAccountId", "Date")
                        .HasDatabaseName("IX_CreditTransaction_Account_Date");

                    b.HasIndex("Date", "CreditAccountId")
                        .HasDatabaseName("IX_CreditTransaction_Date_Account");

                    b.ToTable("CreditTransactions", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_CreditTransaction_Amount_NotZero", "[Amount] <> 0");

                            t.HasCheckConstraint("CK_CreditTransaction_Type_Valid", "[Type] IN ('Consumo', 'Ajuste', 'Devolucion')");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatusId", "CreatedAt")
                        .HasDatabaseName("IX_Customer_Status_CreatedAt");

                    b.ToTable("Customers", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Email_Valid", "[Email] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Customer_Phone_Digits", "[Phone] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasDiscriminator<string>("CustomerType").HasValue("Customer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CustomerAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId", "IsCurrent", "IsPrimary")
                        .HasDatabaseName("IX_CustomerAddress_Current_Primary");

                    b.ToTable("CustomerAddresses", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerAddress_ValidFrom_NotNull", "[ValidFrom] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.TaxInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("TaxInformation", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_TaxInformation_TIN_Valid", "[TaxIdentificationNumber] NOT LIKE '%[^A-Za-z0-9]%'");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.TaxInformationAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<long>("TaxInformationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("TaxInformationId", "IsCurrent", "IsPrimary")
                        .HasDatabaseName("IX_TaxInformationAddress_Current_Primary");

                    b.ToTable("TaxInformationAddresses", "CRM");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("InternationalPhoneCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Iso31661A2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso31661A3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Iso31661NumCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("IX_Countries_CurrencyCode");

                    b.HasIndex("Domain")
                        .HasDatabaseName("IX_Countries_Domain");

                    b.HasIndex("Iso31661A2Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Countries_Iso31661A2Code");

                    b.HasIndex("Iso31661A3Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Countries_Iso31661A3Code");

                    b.HasIndex("Iso31661NumCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Countries_Iso31661NumCode");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Countries_Name");

                    b.ToTable("Countries", "EBOS", t =>
                        {
                            t.HasCheckConstraint("CK_Countries_IsoA2_Length", "LEN([Iso31661A2Code]) = 2");

                            t.HasCheckConstraint("CK_Countries_IsoA3_Length", "LEN([Iso31661A3Code]) = 3");

                            t.HasCheckConstraint("CK_Country_IsoA2_Uppercase", "UPPER([Iso31661A2Code]) = [Iso31661A2Code]");

                            t.HasCheckConstraint("CK_Country_IsoA3_Uppercase", "UPPER([Iso31661A3Code]) = [Iso31661A3Code]");

                            t.HasCheckConstraint("CK_Country_IsoNum_Digits", "[Iso31661NumCode] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.IdentificationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Erased")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("IdentificationTypes", "EBOS");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Statuses", "EBOS");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CorporateCustomer", b =>
                {
                    b.HasBaseType("EBOS.CRM.Domain.Entities.CRM.Customer");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxIdentification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("Customers", "CRM", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Email_Valid", "[Email] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Customer_Phone_Digits", "[Phone] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_CorporateCustomer_TaxId_Valid", "[TaxIdentification] NOT LIKE '%[^A-Za-z0-9]%'");
                        });

                    b.HasDiscriminator().HasValue("Corporate");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.IndividualCustomer", b =>
                {
                    b.HasBaseType("EBOS.CRM.Domain.Entities.CRM.Customer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("IdentificationTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("IdentificationTypeId")
                        .HasDatabaseName("IX_IndividualCustomer_IdentificationTypeId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Email_Valid", "[Email] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Customer_Phone_Digits", "[Phone] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasDiscriminator().HasValue("Individual");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Address", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBOS.CRM.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AddressType");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BankInformation", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Customer", "Customer")
                        .WithOne("BankInformation")
                        .HasForeignKey("EBOS.CRM.Domain.Entities.CRM.BankInformation", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BranchOffice", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.CorporateCustomer", "CorporateCustomer")
                        .WithMany("BranchOffices")
                        .HasForeignKey("CorporateCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorporateCustomer");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BranchOfficeAddress", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Address", "Address")
                        .WithMany("BranchOfficeAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.BranchOffice", "BranchOffice")
                        .WithMany("BranchOfficeAddresses")
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BranchOffice");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CreditAccount", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Customer", "Customer")
                        .WithOne("CreditAccount")
                        .HasForeignKey("EBOS.CRM.Domain.Entities.CRM.CreditAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CreditTransaction", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.CreditAccount", "CreditAccount")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditAccount");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Customer", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.Status", "Status")
                        .WithMany("Customers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CustomerAddress", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Address", "Address")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Customer", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.TaxInformation", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Customer", "Customer")
                        .WithOne("TaxInformation")
                        .HasForeignKey("EBOS.CRM.Domain.Entities.CRM.TaxInformation", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.TaxInformationAddress", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.Address", "Address")
                        .WithMany("TaxInformationAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBOS.CRM.Domain.Entities.CRM.TaxInformation", "TaxInformation")
                        .WithMany("TaxInformationAddresses")
                        .HasForeignKey("TaxInformationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("TaxInformation");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.IndividualCustomer", b =>
                {
                    b.HasOne("EBOS.CRM.Domain.Entities.IdentificationType", "IdentificationType")
                        .WithMany()
                        .HasForeignKey("IdentificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentificationType");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Address", b =>
                {
                    b.Navigation("BranchOfficeAddresses");

                    b.Navigation("CustomerAddresses");

                    b.Navigation("TaxInformationAddresses");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.BranchOffice", b =>
                {
                    b.Navigation("BranchOfficeAddresses");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CreditAccount", b =>
                {
                    b.Navigation("CreditTransactions");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankInformation");

                    b.Navigation("CreditAccount");

                    b.Navigation("CustomerAddresses");

                    b.Navigation("TaxInformation");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.TaxInformation", b =>
                {
                    b.Navigation("TaxInformationAddresses");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.Status", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("EBOS.CRM.Domain.Entities.CRM.CorporateCustomer", b =>
                {
                    b.Navigation("BranchOffices");
                });
#pragma warning restore 612, 618
        }
    }
}
