<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EBOS.Core" Version="1.6.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="..\..\..\..\..\..\Users\juan.pardogarcia\.nuget\packages\ebos.core\1.6.4\contentFiles\any\net8.0\Logo_EBOS_128.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Services\" />
  </ItemGroup>

</Project>
